spring:
  application:
    name: APPLICATION NAME HERE EG- payment-service
  cloud:
    config:
      enabled: false

server:
  port: PORT NUMBER HERE

razorpay:
  key: RAZORPAY KEY
  secret: RAZORPAY SECRET
  webhook: RAZORPAY WEB HOOK
// TO RUN The payment service make sure to enable webhook in razorpay and 
make run the payment service using ngrok as webhook dont make local calls.





eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

